# Cloud Run service manifest for GameHub API (backend)
# Apply with:
#   gcloud run services replace infra/cloudrun/backend.yaml \
#     --region=${REGION} --project=${PROJECT}

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gamehub-api
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: all
        run.googleapis.com/port: "8080"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/client-name: "github-actions"
    spec:
      containers:
        - image: ${REGION}-docker.pkg.dev/${PROJECT}/${AR_REPO:-gamehub}/gamehub-api:${SHA}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CORS_ALLOWED_ORIGINS
              value: ${FRONTEND_URL:-http://localhost:3000}
            - name: APP_JWT_SECRET
              valueSource:
                secretKeyRef:
                  name: APP_JWT_SECRET
                  key: latest
            - name: APP_JWT_EXPIRATION_MS
              value: "86400000"
            - name: DB_HOST
              value: ${DB_HOST:-10.0.0.3}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: ${DB_NAME:-gamesdb}
            - name: DB_USER
              valueSource:
                secretKeyRef:
                  name: SPRING_DATASOURCE_USERNAME
                  key: latest
            - name: DB_PASSWORD
              valueSource:
                secretKeyRef:
                  name: SPRING_DATASOURCE_PASSWORD
                  key: latest
            - name: SPRING_DATASOURCE_URL
              valueSource:
                secretKeyRef:
                  name: SPRING_DATASOURCE_URL
                  key: latest
            - name: SPRING_REDIS_HOST
              value: ${REDIS_HOST:-}
            - name: SPRING_REDIS_PORT
              value: ${REDIS_PORT:-6379}
            - name: STOMP_USER_MSGS_PER_MIN
              value: ${STOMP_USER_MSGS_PER_MIN:-300}
            - name: STOMP_GUEST_MSGS_PER_MIN
              value: ${STOMP_GUEST_MSGS_PER_MIN:-120}
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
      timeoutSeconds: 60
      # Uncomment if using Private IP to Cloud SQL/Memorystore
      # vpcAccess:
      #   connector: projects/${PROJECT}/locations/${REGION}/connectors/${VPC_CONNECTOR}
  traffic:
    - latestRevision: true
      percent: 100
