steps:
  # Build the application (Java 21)
  - name: "maven:3.9-eclipse-temurin-21"
    entrypoint: mvn
    args: [ "-B", "clean", "package", "-DskipTests" ]

  # Configure Docker to push to Artifact Registry
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet

  # Build the Docker image (Artifact Registry)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "build", "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}", "." ]

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}" ]

  # Deploy to Cloud Run (port 8080)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--set-env-vars"
      - "SPRING_PROFILES_ACTIVE=prod"

# Store images in Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}"

# Define substitution variables
substitutions:
  _REGION: northamerica-northeast1
  _AR_REPO: gamehub
  _SERVICE: gamehub-api
